### ISSUE TITLE
vboot for APU

### ISSUE THREAD

**Issue by pkubaj** [pcengines/coreboot#185]
You spoke about TPM and vboot on APU on ECC2017.

Could you upload the necessary FMD file to the repo and make a simple how-to for vboot-enabled coreboot?

That would probably make APU the 1st device with vboot that is not a Chromebook :)

**Comment by pietrushnic** [comment]
@pkubaj yes, we getting this inquiry not only from you, but right now we are very busy with various other issues. Our code was note accepted that time to mainline [this was the review](https://review.coreboot.org/#/c/coreboot/+/21983/)/. Quite a lot changed since that time, but we plan to do something with that in Q3 2018 hopefully.

**Comment by miczyg1** [comment]
We have added initial support of vboot and measured boot mode. It will be evolved and improved over time

https://github.com/pcengines/coreboot/pull/303

I believe we can close the issue.

**Comment by miczyg1** [comment]
Building details: https://github.com/pcengines/apu2-documentation/blob/master/docs/apu2_vboot.md

**Comment by pkubaj** [comment]
Is it possible to use it on APU1?

**Comment by miczyg1** [comment]
@pkubaj I am not sure about sufficient free space on SPI flash. 2MiB may be too small. But with 8MiB it will go for sure.
