### ISSUE TITLE
bios update error on apu2c4

### ISSUE THREAD

**Issue by hdatma** [pcengines/coreboot#80]
bios: http://pcengines.ch/file/apu2_v4.0.11.rom.tar.gz

```
root@box:/media/SYSLINUX# flashrom -w apu2_v4.0.11.rom -p internal
flashrom v0.9.8-r1888 on Linux 3.16.6-tinycore (i686)
flashrom is free software, get the source code at http://www.flashrom.org

Calibrating delay loop... delay loop is unreliable, trying to continue OK.
coreboot table found at 0xdffae000.
Found chipset "AMD FCH".
Enabling flash write... OK.
Found Winbond flash chip "W25Q64.V" (8192 kB, SPI) mapped at physical address 0xff800000.
This coreboot image (PC Engines:PC Engines apu2) does not appear to
be correct for the detected mainboard (PC Engines:PCEngines apu2).
Aborting. You can override this with -p internal:boardmismatch=force.
```

**Comment by pietrushnic** [comment]
@hdatma this is known issue. Unfortunately legacy BIOS with which boards were shipped contain different string in SMBIOS/DMI tables. Unfortunately there is not much we can do with that. You can force flashing as commend suggest. We also have [modified flashrom](https://github.com/pcengines/flashrom/tree/apu_support) which supress this warining by setting `boardmismatch=force` by default.

**Comment by hdatma** [comment]
Looks good.

```
PC Engines apu2
coreboot build 20170724
BIOS version v4.0.11
4080 MB ECC DRAM

SeaBIOS (version rel-1.10.2.1)

Press F10 key now for boot menu

Select boot device:

1. USB MSC Drive VendorCo ProductCode 2.00
2. SD card SD04G 3796MiB
3. Payload [memtest]
4. Payload [setup]
```

**Comment by hdatma** [comment]
There are two versions on site*: 4.0.11 and 4.6.0. Which one is best?

http://pcengines.ch/howto.htm#bios

**Comment by pietrushnic** [comment]
@hdatma second round and all further will be good since SMBIOS/DMI table is not correct. Please take a look at [Binary releases section in README](https://github.com/pcengines/apu2-documentation#binary-releases). There is link to changelog, based on which you can decide which one fits your needs. If you like bleeding edge I would recommend 4.6.x. We will abandon improvements in 4.0.x soon.

**Comment by hdatma** [comment]
I like stable and reliable.

**Comment by Strykar** [comment]
@pietrushnic I just tried 4.6.0 on my APU2 and the BIOS no longer has the option to enable/disable UART C and D. Why was this removed?

**Comment by pietrushnic** [comment]
@Strykar this option was never available in mainline coreboot, but was part of legacy version. Runtime configuration was added in recent release [4.6.3](https://github.com/pcengines/coreboot/blob/coreboot-4.6.x/CHANGELOG.md#v463---2017-10-30). `README.md` contain links only to firmware binaries verified by PC Engines. If you want to try different version you can build it from source. If you need that option now and don't want to build firmware by your own please try recent legacy version which is in [this section](https://github.com/pcengines/apu2-documentation#legacy)

**Comment by pietrushnic** [comment]
@hdatma @Strykar If there are no other problems related I would like to close this issue.

**Comment by hdatma** [comment]
Sure, go ahead! Thanks!

**Comment by hdatma** [comment]
Sure, go ahead! Thanks!

**Comment by piu130** [comment]
@pietrushnic is 4.6.x now stable? Or still bleeding edge?

**Comment by pietrushnic** [comment]
@piu130 it depends what you consider stable. There is no such thing like stable coreboot release - I was surprised also, but it happens that coreboot releases are arbitrary points in time. There are no extensive quality checks behind that. We try to do validation on our own but it is not an easy thing - we plan to publish our automated tests results soon, so people can see what are the things that were confirmed. Of course, we are not able to validate all configurations and have to rely on the community.

I also don't know what you mean by "bleeding edge". `coreboot-4.6.x` is quite far from upstream master branch, so for sure this is not the latest greatest coreboot version.

Anyone who tries to flash the firmware on apuX should have a very good reason behind that, if there is no reason then please do not update. If you want the update please make sure you have a fallback mechanism like [spi1a](http://pcengines.ch/spi1a.htm). We are not responsible for any damage caused by firmware upgrades.
